name: opennow
description: A Flutter app for shop owners to show if their shop is open/closed and for customers to find open shops.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # State Management
  provider: ^6.1.1
  
  # Background processing
  workmanager: ^0.5.2
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add app icon and splash screen assets here
  assets:
    - assets/images/
    
  # App icon configuration (uncomment and configure when you add icon)
  # flutter_icons:
  #   android: true
  #   ios: true
  #   image_path: "assets/images/app_icon.png"